[project]
name = "dcat-br"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyshacl>=0.31.0",
    "python-dotenv>=1.2.1",
    "rdflib>=7.5.0",
]
